Add support for freetype-gl
cpp-pm/hunter pull request #249
Opened 2020-08-22 01:54 UTC by caseymcc

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/caseymcc/hunter-testing/builds/34793318
  * https://travis-ci.org/github/caseymcc/hunter-testing/builds/720109095

* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
  see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/74

Need a package repo for https://github.com/caseymcc/freetype-gl/tree/hunter and release.

2020-08-24 14:54 UTC, rbsheth commented
@caseymcc https://github.com/cpp-pm/freetype-gl

2020-08-31 16:10 UTC, caseymcc commented
PR created for package https://github.com/cpp-pm/freetype-gl/pull/1

2020-09-09 01:15 UTC, rbsheth commented
@caseymcc https://github.com/cpp-pm/freetype-gl/releases/tag/v0.0.0-1a8c007-p0

2020-09-10 19:07 UTC, caseymcc commented
@rbsheth update with the cpp-pm package release, pr for the test at https://github.com/cpp-pm/hunter-testing/pull/74

https://travis-ci.org/github/caseymcc/hunter-testing/builds/726012729
https://ci.appveyor.com/project/caseymcc/hunter-testing/builds/35136911

2020-09-23 13:05 UTC, rbsheth requested changes

2020-09-23 13:05 UTC, rbsheth commented on cmake/projects/freetype-gl/hunter.cmake
> +    "20.21.6-p0" #project has no releases so usinging date Y.M.D-patch
Version needs to match the release name. So `v0.0.0-1a8c007-p0`

2020-09-23 13:05 UTC, rbsheth commented on cmake/projects/freetype/hunter.cmake
> +    "https://github.com/caseymcc/freetype/archive/v2.9.1-p4.tar.gz"
PR needed for your freetype changes here: https://github.com/cpp-pm/freetype

2020-10-09 20:28 UTC, caseymcc commented
updated to use the github actions CI

2020-10-13 14:02 UTC, caseymcc commented
@rbsheth What is missing for this PR?

2020-10-14 14:54 UTC, rbsheth reviewed
@caseymcc couple small things need fixing. Then it will be merged!

2020-10-14 14:54 UTC, rbsheth commented on cmake/projects/freetype-gl/ci/build.sh
> +# Install Python package 'requests'
This should use the base script by default: https://hunter.readthedocs.io/en/latest/creating-new/test/ci.html#override-default-tests

Something like:
```
sudo apt-get install libgl1-mesa-dev

bash .github/workflows/ci/build.sh
```

2020-10-14 14:54 UTC, rbsheth commented on cmake/projects/freetype-gl/hunter.cmake
> +    "0.0.0-1a8c007-p0" #project has no releases so usinging date Y.M.D-patch
Nit: spelling

2020-10-14 14:54 UTC, rbsheth commented on docs/spelling.txt
> +freetype
You can just add the keywords at the top of the package.rst file. Don't edit this one.

2020-10-14 14:54 UTC, rbsheth commented on examples/freetype-gl/main.cpp
> +#include <iostream> // std::cout
You're not using iostream here?

2020-10-14 14:54 UTC, rbsheth commented on examples/freetype-gl/main.cpp
> +    texture_glyph_t *emptyGlph=texture_glyph_new();
Nit: spelling

2020-10-14 14:54 UTC, rbsheth commented on docs/packages/pkg/freetype-gl.rst
> +-  `Hunterized <https://github.com/hunter-packages/freetype-gl>`__
Not hunter-packages, cpp-pm

2020-10-14 14:54 UTC, rbsheth commented on cmake/projects/freetype-gl/ci/matrix.json
> +]
Nit: newline at end

2020-10-14 14:54 UTC, rbsheth commented on cmake/projects/freetype-gl/ci/build.sh
> +fi
Nit: newline at end

2020-11-02 16:29 UTC, rbsheth approved these changes

2020-11-02 16:29 UTC, merged

2020-11-02 16:46 UTC, rahulshethsc commented
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.280