Update 'harfbuzz' package to v2.8.0-p0
cpp-pm/hunter pull request #507
Opened 2022-01-12 09:08 UTC by drodin

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* This update will fix a few toolchains.
  - iOS
  - mingw
  - msys

2022-01-12 13:45 UTC, NeroBurner requested changes

2022-01-12 13:45 UTC, NeroBurner commented on cmake/projects/harfbuzz/hunter.cmake
> +hunter_add_version(
please append the newest version at the end of the list. This makes the diffs of various tools nicer formatted

2022-01-13 08:03 UTC, NeroBurner approved these changes

2022-01-13 19:14 UTC, rbsheth approved these changes

2022-01-13 19:15 UTC, merged

2022-01-13 19:17 UTC, rbsheth commented
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.321