Add asio-grpc
cpp-pm/hunter pull request #554
Opened 2022-04-24 15:55 UTC by Tradias

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

2022-04-24 16:34 UTC, Tradias commented
Is there anything I can or must do about the failing pipelines? It seems that it fails to build gRPC, did I hunterize my project incorrectly (see [CMakeLists.txt](https://github.com/Tradias/asio-grpc/blob/master/CMakeLists.txt#L17-L23) and  [AsioGrpcHunter.cmake](https://github.com/Tradias/asio-grpc/blob/master/cmake/AsioGrpcHunter.cmake))? I created a small test project locally that consumes asio-grpc through hunter it everything works successfully.

Also, I know that `hunter_add_version` currently points at the master branch of asio-grpc. I will release a new version (1.6.0) once you can confirm that asio-grpc has been hunterized correctly.

2022-04-24 17:11 UTC, NeroBurner commented
I just looked at a failing build, not on the PR itself or the hunterized project. But here are my findings and suspicions

https://github.com/cpp-pm/hunter/runs/6147671151?check_suite_focus=true#step:7:5713

```
/usr/bin/ld: /home/runner/work/hunter/hunter/_testing/Hunter/_Base/eca1947/9dcf50b/8c25157/Install/lib/libcares.a(ares_strerror.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```



you seem to be creating a shared library (is this intended?), but one of the dependencies for the shared library was built as static library without relocation support. The static library needs to be compiled with `-fPIC` flag. This flag is default set in MSVC, but unfortunately not on GCC/Clang (I think because of historic reasons, but I'm not sure). Two ways to fix this

- the dependency (or all dependencies) must set the `-fPIC` flag to compile static libraries (or generally libraries, but -fPIC is redundant for shared libraries)
- use a cmake toolchain file, where `-fPIC` is set as a compiler flag

I prefer the first fix, as the second one is more of a workaround in my honest opinion

2022-04-24 17:30 UTC, Tradias commented
Hi, thank you for the quick feedback. Asio-grpc is a header only library and does not need any dependencies to be installed, but in order to conform to the hunter guidelines it should list its runtime dependencies through `hunter_add_package`. At least, that is how I understood it from other PR's (e.g. restinio). One of these dependencies is gRPC, which builds c-ares internally . I think my PR and asio-grpc does not and should not influence how gRPC is being build by hunter. I suspect that the CI for gRPC itself here on hunter would also fail with the same error.

2022-04-24 18:53 UTC, NeroBurner commented
ah, the build table https://cpp-pm.github.io/hunter/ (search for gRPC) states, that it builds only with a `fpic` enabled toolchain

This is good, because one toolchain here `gcc-9-cxx17-fpic` successfully builds. `gRPC` additionally was able to build on `gcc-8-cxx17-fpic`. Is gcc-8 not supported by `asio-grpc`? Not a blocker if it isn't

2022-04-24 18:58 UTC, NeroBurner requested changes

2022-04-24 18:58 UTC, NeroBurner commented on docs/packages/pkg/asio-grpc.rst
> +-  Added by `Tradias <https://github.com/Tradias>`__ (`pr-N <https://github.com/cpp-pm/hunter/pull/N>`__)
```suggestion
-  Added by `Tradias <https://github.com/Tradias>`__ (`pr-554 <https://github.com/cpp-pm/hunter/pull/554>`__)
```

2022-04-24 18:58 UTC, NeroBurner commented on cmake/projects/asio-grpc/hunter.cmake
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
You can add yourself here and update the year

```suggestion
# Copyright (c) 2022, Tradias
```

2022-04-24 18:58 UTC, NeroBurner commented on cmake/projects/asio-grpc/hunter.cmake
> +    "https://github.com/Tradias/asio-grpc/archive/refs/heads/master.zip "
just leaving a note here to not forget about the release tag later

2022-04-24 18:58 UTC, NeroBurner commented on examples/asio-grpc/boo.cpp
> +}
could you use something from the header here, to make it double sure, that the include did work?

2022-04-25 06:36 UTC, Tradias commented
Good catch. Asio-grpc requires the `ASIO_GRPC_USE_BOOST_CONTAINER` CMake arg to compile with GCC 8. I could change its default value for compilers known to need it, will do that.

2022-04-27 08:48 UTC, NeroBurner requested changes
Nice progress on this PR. Just some small Licensing and testing addition, then we're good to go

2022-04-27 08:48 UTC, NeroBurner commented on examples/asio-grpc/CMakeLists.txt
> +# DOCUMENTATION_END }
In other examples we additionally do a second `find_package()` to make sure the imported library target creation is well behaved. And please add a test if the license of the package is well defined

See https://github.com/cpp-pm/hunter/blob/master/examples/Eigen/CMakeLists.txt#L20 for pointers how to do that

2022-04-27 09:03 UTC, NeroBurner commented on examples/asio-grpc/CMakeLists.txt
> +# DOCUMENTATION_END }
See https://hunter.readthedocs.io/en/latest/user-guides/cmake-user/using-license-files.html?highlight=HUNTER_INSTALL_LICENSE_FILES#using-license-files for documentation about license files and how hunter finds them

2022-04-27 09:38 UTC, NeroBurner commented on examples/asio-grpc/CMakeLists.txt
> +endforeach()
small nitpick, non-blocking: please add a newline at the end of files

```suggestion
endforeach()

```

2022-04-27 11:47 UTC, NeroBurner approved these changes
LGTM thank you for your contribution!

2022-04-27 11:50 UTC, merged