check and fix packages urls
cpp-pm/hunter pull request #575
Opened 2022-06-13 04:07 UTC by drodin

* script to go through packages and check if urls are still valid
* manual clean up of non existent/changed urls
* some cosmetic fixes for easier automation checks on packages

This fixes: https://github.com/cpp-pm/hunter/issues/546 https://github.com/cpp-pm/hunter/issues/540 and https://github.com/cpp-pm/hunter/issues/191

2022-06-13 09:06 UTC, NeroBurner requested changes
Thank you very much for this contribution! Checking the download URLs is a VERY good idea!

I'd like to extend the script a bit. Maybe it would be a good idea to check the projects when they are changed in the CI. On the one hand checking the project URL when a contributor comes along and gets a seemingly unconnected error because of an old package URL. Otherwise it would be great to check the URLs somewhere/somewhen

@rbsheth what do you think?

2022-06-13 09:14 UTC, drodin commented on maintenance/check-urls.py
> +checkedFile = join(hunterDir, 'checked.txt')
done https://github.com/cpp-pm/hunter/pull/575/commits/9698dd773f672e069075f48b3761492e640c9820

2022-06-13 09:39 UTC, drodin commented on maintenance/check-urls.py
> +projectsFiles = join(projectsDir, '**', '*.cmake')
https://github.com/cpp-pm/hunter/pull/575/commits/ac61f83550672e517ef0383d2a0d9d2488d04c13

2022-06-14 05:43 UTC, NeroBurner approved these changes
LGTM, only question left for me is if and how we can include this marvelous piece of code in the CI :thinking:

2022-06-15 10:03 UTC, drodin commented
> LGTM, only question left for me is if and how we can include this marvelous piece of code in the CI 🤔

its possible to include this script into build.sh/cmd. add an exit code to it, or just check  if 'checked.txt' file is present and zero size

2022-06-16 19:08 UTC, rbsheth commented
> Thank you very much for this contribution! Checking the download URLs is a VERY good idea!
> 
> I'd like to extend the script a bit. Maybe it would be a good idea to check the projects when they are changed in the CI. On the one hand checking the project URL when a contributor comes along and gets a seemingly unconnected error because of an old package URL. Otherwise it would be great to check the URLs somewhere/somewhen
> 
> @rbsheth what do you think?

Yeah, it would be useful to weed out broken packages. We can add it to CI

2022-08-18 12:00 UTC, merged

2022-08-18 12:03 UTC, NeroBurner commented
created a new Issue for the adding of the script to the CI

https://github.com/cpp-pm/hunter/issues/598

2022-08-25 13:21 UTC, NeroBurner commented
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.4