New Package: Intel oneTBB
cpp-pm/hunter pull request #600
Opened 2022-08-24 19:24 UTC by craffael

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

2022-08-24 19:47 UTC, NeroBurner requested changes
just some small nitpicks, thank you for the contribution

2022-08-24 19:47 UTC, NeroBurner commented on cmake/projects/oneTBB/hunter.cmake
> +	TBB_STRICT=OFF
use spaces for indentation, please don't mix it up

```suggestion
    TBB_STRICT=OFF
```

2022-08-24 19:47 UTC, NeroBurner commented on cmake/projects/oneTBB/hunter.cmake
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
please update copyright

2022-08-24 20:06 UTC, craffael commented on examples/oneTBB/CMakeLists.txt
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
Do you want me to update the year (replace 2020 by 2022)? And should I do this change also in `examples/foo/CMakeLists.txt`? That way the template which is used in [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html#create-example) would be up to date...

2022-08-24 20:07 UTC, craffael commented on examples/oneTBB/CMakeLists.txt
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
btw. Thanks for the almost immediate review!

2022-08-24 20:11 UTC, NeroBurner commented on examples/oneTBB/CMakeLists.txt
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
I'd say adding yourself and replace the year with 2022, something like the following (replace the name, that you want to have there)

```suggestion
# Copyright (c) 2022, craffael
```

If the guide is out of date a PR to fix that would be very much appreciated :pray:

2022-08-24 20:15 UTC, NeroBurner commented on examples/oneTBB/CMakeLists.txt
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
you're welcome :)

2022-08-24 20:19 UTC, craffael commented on examples/oneTBB/CMakeLists.txt
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
thx for the suggestion and the fast review! I think I'll make a separate PR for the guide.

2022-08-24 20:19 UTC, craffael commented on cmake/projects/oneTBB/hunter.cmake
> +# Copyright (c) 2016-2020, Rahul Sheth, Ruslan Baratov
done.

2022-08-24 20:20 UTC, NeroBurner approved these changes
LGTM

yes please, a separate PR would be very good :)

2022-08-24 20:21 UTC, merged

2022-08-25 13:13 UTC, NeroBurner commented
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.5