Update minimum CMake to v3.10
cpp-pm/hunter pull request #769
Opened 2024-12-17 14:05 UTC by hjmallon

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.5 (minimum requirement for Hunter). **[No]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**

---

Also needs a gate update after https://github.com/cpp-pm/gate/pull/18

2025-04-02 13:51 UTC, Waarbubble commented
Is there an ETA on when this can be approved, or where in the progress this is?

2025-04-10 07:09 UTC, NeroBurner requested changes
minor documentation update and then we're good to go!

Thanks for the PR

2025-04-10 07:09 UTC, NeroBurner commented on docs/old-wiki/usr.adding.new.package.custom.scheme.md
> +must to be checked manually for each custom build scheme (see [CMake package default behaviour](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour))
what's the change of this line, I don't see a difference in GitHub view :thinking:

2025-04-10 07:09 UTC, NeroBurner commented on docs/quick-start/cmake.rst
> +  * `CMake release notes <https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features>`__
for completeness add a link to this PR
```suggestion
  * `CMake release notes <https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features>`__
  * Since: `PR #769 <https://github.com/cpp-pm/hunter/pull/769>`__
```

2025-04-16 13:51 UTC, hjmallon commented on docs/old-wiki/usr.adding.new.package.custom.scheme.md
> +must to be checked manually for each custom build scheme (see [CMake package default behaviour](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour))
My editor has inserted a newline at the end

2025-04-16 13:52 UTC, hjmallon commented
I have updated the gate submodule and also found some more places in `examples` where the older version was set

2025-04-25 12:37 UTC, chfast commented
How are we doing here?

2025-04-28 07:20 UTC, NeroBurner approved these changes
looking good! Thanks for the update and the sensible format and trailing line fixes

2025-04-28 07:21 UTC, merged

2025-05-19 11:38 UTC, NeroBurner commented
yes, I just want to finish https://github.com/cpp-pm/hunter/pull/780 such that the CI-toolchains work again and are updated

2025-06-06 07:30 UTC, NeroBurner commented
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.26.0